pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - main
    - feature/*

name: 1.0.$(Build.BuildId)

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish win-x64'
      dependsOn: []
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(system.teamProject).csproj'
        zipAfterPublish: false
        modifyOutputPath: false
        arguments: '-r win-x64 --output $(Build.ArtifactStagingDirectory)/win-x64 -p:Version=$(Build.BuildNumber)' 

    - task: DotNetCoreCLI@2
      displayName: 'Publish win-x86'
      dependsOn: []
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(system.teamProject).csproj'
        zipAfterPublish: false
        modifyOutputPath: false
        arguments: '-r win-x86 --output $(Build.ArtifactStagingDirectory)/win-x86 -p:Version=$(Build.BuildNumber)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish osx-x64'
      dependsOn: []
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(system.teamProject).csproj'
        zipAfterPublish: false
        modifyOutputPath: false
        arguments: '-r osx-x64 --output $(Build.ArtifactStagingDirectory)/osx-x64 -p:Version=$(Build.BuildNumber)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: '$(system.teamProject)'        

- stage: CreateGitHubRelease
  displayName: Create GitHub Release
  jobs:
  - job: Release
    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        artifact: '$(system.teamProject)'
        path: $(Pipeline.Workspace)

    - task: GitHubRelease@1
      displayName: 'Create GitHub Release'
      inputs:
        gitHubConnection: 'GitHub Release'
        repositoryName: sboulema/VSLauncher
        action: Create
        title: 'v$(Build.BuildNumber)'
        assets: '$(Pipeline.Workspace)/**/*.exe'
        tagSource: 'userSpecifiedTag'
        tag: $(Build.BuildNumber)